export default function handler(req, res) {
  const wordPool = [
    // Animals (100 words)
  { word: "elephant", category: "Animal" },
  { word: "tiger", category: "Animal" },
  { word: "dolphin", category: "Animal" },
  { word: "penguin", category: "Animal" },
  { word: "kangaroo", category: "Animal" },
  { word: "giraffe", category: "Animal" },
  { word: "rhinoceros", category: "Animal" },
  { word: "cheetah", category: "Animal" },
  { word: "hippopotamus", category: "Animal" },
  { word: "crocodile", category: "Animal" },
  { word: "leopard", category: "Animal" },
  { word: "chimpanzee", category: "Animal" },
  { word: "orangutan", category: "Animal" },
  { word: "gorilla", category: "Animal" },
  { word: "zebra", category: "Animal" },
  { word: "lion", category: "Animal" },
  { word: "wolf", category: "Animal" },
  { word: "bear", category: "Animal" },
  { word: "fox", category: "Animal" },
  { word: "rabbit", category: "Animal" },
  { word: "deer", category: "Animal" },
  { word: "moose", category: "Animal" },
  { word: "eagle", category: "Animal" },
  { word: "hawk", category: "Animal" },
  { word: "owl", category: "Animal" },
  { word: "parrot", category: "Animal" },
  { word: "flamingo", category: "Animal" },
  { word: "peacock", category: "Animal" },
  { word: "swan", category: "Animal" },
  { word: "duck", category: "Animal" },
  { word: "goose", category: "Animal" },
  { word: "chicken", category: "Animal" },
  { word: "turkey", category: "Animal" },
  { word: "ostrich", category: "Animal" },
  { word: "sparrow", category: "Animal" },
  { word: "robin", category: "Animal" },
  { word: "cardinal", category: "Animal" },
  { word: "hummingbird", category: "Animal" },
  { word: "woodpecker", category: "Animal" },
  { word: "crow", category: "Animal" },
  { word: "raven", category: "Animal" },
  { word: "seagull", category: "Animal" },
  { word: "pelican", category: "Animal" },
  { word: "shark", category: "Animal" },
  { word: "whale", category: "Animal" },
  { word: "octopus", category: "Animal" },
  { word: "jellyfish", category: "Animal" },
  { word: "starfish", category: "Animal" },
  { word: "seahorse", category: "Animal" },
  { word: "turtle", category: "Animal" },
  { word: "frog", category: "Animal" },
  { word: "snake", category: "Animal" },
  { word: "lizard", category: "Animal" },
  { word: "iguana", category: "Animal" },
  { word: "chameleon", category: "Animal" },
  { word: "salamander", category: "Animal" },
  { word: "butterfly", category: "Animal" },
  { word: "moth", category: "Animal" },
  { word: "beetle", category: "Animal" },
  { word: "spider", category: "Animal" },
  { word: "scorpion", category: "Animal" },
  { word: "centipede", category: "Animal" },
  { word: "dragonfly", category: "Animal" },
  { word: "grasshopper", category: "Animal" },
  { word: "cricket", category: "Animal" },
  { word: "ant", category: "Animal" },
  { word: "bee", category: "Animal" },
  { word: "wasp", category: "Animal" },
  { word: "fly", category: "Animal" },
  { word: "mosquito", category: "Animal" },
  { word: "ladybug", category: "Animal" },
  { word: "caterpillar", category: "Animal" },
  { word: "worm", category: "Animal" },
  { word: "snail", category: "Animal" },
  { word: "slug", category: "Animal" },
  { word: "crab", category: "Animal" },
  { word: "lobster", category: "Animal" },
  { word: "shrimp", category: "Animal" },
  { word: "clam", category: "Animal" },
  { word: "oyster", category: "Animal" },
  { word: "mussel", category: "Animal" },
  { word: "squid", category: "Animal" },
  { word: "eel", category: "Animal" },
  { word: "salmon", category: "Animal" },
  { word: "trout", category: "Animal" },
  { word: "bass", category: "Animal" },
  { word: "tuna", category: "Animal" },
  { word: "goldfish", category: "Animal" },
  { word: "piranha", category: "Animal" },
  { word: "stingray", category: "Animal" },
  { word: "hamster", category: "Animal" },
  { word: "guinea pig", category: "Animal" },
  { word: "ferret", category: "Animal" },
  { word: "hedgehog", category: "Animal" },
  { word: "squirrel", category: "Animal" },
  { word: "chipmunk", category: "Animal" },
  { word: "beaver", category: "Animal" },
  { word: "otter", category: "Animal" },
  { word: "seal", category: "Animal" },
  { word: "walrus", category: "Animal" },
  { word: "polar bear", category: "Animal" },
  { word: "panda", category: "Animal" },
  { word: "koala", category: "Animal" },
  { word: "sloth", category: "Animal" },
  { word: "armadillo", category: "Animal" },

  // Countries (100 words)
  { word: "canada", category: "Country" },
  { word: "united states", category: "Country" },
  { word: "mexico", category: "Country" },
  { word: "brazil", category: "Country" },
  { word: "argentina", category: "Country" },
  { word: "chile", category: "Country" },
  { word: "peru", category: "Country" },
  { word: "colombia", category: "Country" },
  { word: "venezuela", category: "Country" },
  { word: "ecuador", category: "Country" },
  { word: "bolivia", category: "Country" },
  { word: "uruguay", category: "Country" },
  { word: "paraguay", category: "Country" },
  { word: "guyana", category: "Country" },
  { word: "suriname", category: "Country" },
  { word: "france", category: "Country" },
  { word: "germany", category: "Country" },
  { word: "italy", category: "Country" },
  { word: "spain", category: "Country" },
  { word: "portugal", category: "Country" },
  { word: "united kingdom", category: "Country" },
  { word: "ireland", category: "Country" },
  { word: "netherlands", category: "Country" },
  { word: "belgium", category: "Country" },
  { word: "switzerland", category: "Country" },
  { word: "austria", category: "Country" },
  { word: "sweden", category: "Country" },
  { word: "norway", category: "Country" },
  { word: "denmark", category: "Country" },
  { word: "finland", category: "Country" },
  { word: "iceland", category: "Country" },
  { word: "poland", category: "Country" },
  { word: "czech republic", category: "Country" },
  { word: "slovakia", category: "Country" },
  { word: "hungary", category: "Country" },
  { word: "romania", category: "Country" },
  { word: "bulgaria", category: "Country" },
  { word: "greece", category: "Country" },
  { word: "croatia", category: "Country" },
  { word: "slovenia", category: "Country" },
  { word: "bosnia", category: "Country" },
  { word: "serbia", category: "Country" },
  { word: "montenegro", category: "Country" },
  { word: "albania", category: "Country" },
  { word: "macedonia", category: "Country" },
  { word: "russia", category: "Country" },
  { word: "ukraine", category: "Country" },
  { word: "belarus", category: "Country" },
  { word: "lithuania", category: "Country" },
  { word: "latvia", category: "Country" },
  { word: "estonia", category: "Country" },
  { word: "moldova", category: "Country" },
  { word: "georgia", category: "Country" },
  { word: "armenia", category: "Country" },
  { word: "azerbaijan", category: "Country" },
  { word: "turkey", category: "Country" },
  { word: "cyprus", category: "Country" },
  { word: "china", category: "Country" },
  { word: "japan", category: "Country" },
  { word: "south korea", category: "Country" },
  { word: "north korea", category: "Country" },
  { word: "mongolia", category: "Country" },
  { word: "taiwan", category: "Country" },
  { word: "india", category: "Country" },
  { word: "pakistan", category: "Country" },
  { word: "bangladesh", category: "Country" },
  { word: "sri lanka", category: "Country" },
  { word: "nepal", category: "Country" },
  { word: "bhutan", category: "Country" },
  { word: "maldives", category: "Country" },
  { word: "myanmar", category: "Country" },
  { word: "thailand", category: "Country" },
  { word: "laos", category: "Country" },
  { word: "cambodia", category: "Country" },
  { word: "vietnam", category: "Country" },
  { word: "malaysia", category: "Country" },
  { word: "singapore", category: "Country" },
  { word: "brunei", category: "Country" },
  { word: "indonesia", category: "Country" },
  { word: "philippines", category: "Country" },
  { word: "timor-leste", category: "Country" },
  { word: "australia", category: "Country" },
  { word: "new zealand", category: "Country" },
  { word: "papua new guinea", category: "Country" },
  { word: "fiji", category: "Country" },
  { word: "vanuatu", category: "Country" },
  { word: "samoa", category: "Country" },
  { word: "tonga", category: "Country" },
  { word: "palau", category: "Country" },
  { word: "micronesia", category: "Country" },
  { word: "marshall islands", category: "Country" },
  { word: "nauru", category: "Country" },
  { word: "kiribati", category: "Country" },
  { word: "tuvalu", category: "Country" },
  { word: "solomon islands", category: "Country" },
  { word: "egypt", category: "Country" },
  { word: "libya", category: "Country" },
  { word: "tunisia", category: "Country" },
  { word: "algeria", category: "Country" },
  { word: "morocco", category: "Country" },
  { word: "sudan", category: "Country" },
  { word: "ethiopia", category: "Country" },
  { word: "kenya", category: "Country" },
  { word: "uganda", category: "Country" },
  { word: "tanzania", category: "Country" },
  { word: "rwanda", category: "Country" },

  // Technology (100 words)
  { word: "javascript", category: "Technology" },
  { word: "python", category: "Technology" },
  { word: "java", category: "Technology" },
  { word: "html", category: "Technology" },
  { word: "css", category: "Technology" },
  { word: "react", category: "Technology" },
  { word: "angular", category: "Technology" },
  { word: "vue", category: "Technology" },
  { word: "nodejs", category: "Technology" },
  { word: "express", category: "Technology" },
  { word: "mongodb", category: "Technology" },
  { word: "mysql", category: "Technology" },
  { word: "postgresql", category: "Technology" },
  { word: "redis", category: "Technology" },
  { word: "docker", category: "Technology" },
  { word: "kubernetes", category: "Technology" },
  { word: "aws", category: "Technology" },
  { word: "azure", category: "Technology" },
  { word: "google cloud", category: "Technology" },
  { word: "firebase", category: "Technology" },
  { word: "git", category: "Technology" },
  { word: "github", category: "Technology" },
  { word: "gitlab", category: "Technology" },
  { word: "bitbucket", category: "Technology" },
  { word: "jenkins", category: "Technology" },
  { word: "travis", category: "Technology" },
  { word: "circleci", category: "Technology" },
  { word: "webpack", category: "Technology" },
  { word: "babel", category: "Technology" },
  { word: "eslint", category: "Technology" },
  { word: "prettier", category: "Technology" },
  { word: "jest", category: "Technology" },
  { word: "cypress", category: "Technology" },
  { word: "selenium", category: "Technology" },
  { word: "puppeteer", category: "Technology" },
  { word: "graphql", category: "Technology" },
  { word: "rest api", category: "Technology" },
  { word: "json", category: "Technology" },
  { word: "xml", category: "Technology" },
  { word: "yaml", category: "Technology" },
  { word: "bootstrap", category: "Technology" },
  { word: "tailwind", category: "Technology" },
  { word: "sass", category: "Technology" },
  { word: "less", category: "Technology" },
  { word: "typescript", category: "Technology" },
  { word: "php", category: "Technology" },
  { word: "laravel", category: "Technology" },
  { word: "symfony", category: "Technology" },
  { word: "codeigniter", category: "Technology" },
  { word: "ruby", category: "Technology" },
  { word: "rails", category: "Technology" },
  { word: "django", category: "Technology" },
  { word: "flask", category: "Technology" },
  { word: "spring", category: "Technology" },
  { word: "hibernate", category: "Technology" },
  { word: "maven", category: "Technology" },
  { word: "gradle", category: "Technology" },
  { word: "android", category: "Technology" },
  { word: "ios", category: "Technology" },
  { word: "swift", category: "Technology" },
  { word: "kotlin", category: "Technology" },
  { word: "flutter", category: "Technology" },
  { word: "react native", category: "Technology" },
  { word: "xamarin", category: "Technology" },
  { word: "cordova", category: "Technology" },
  { word: "ionic", category: "Technology" },
  { word: "unity", category: "Technology" },
  { word: "unreal engine", category: "Technology" },
  { word: "blender", category: "Technology" },
  { word: "photoshop", category: "Technology" },
  { word: "illustrator", category: "Technology" },
  { word: "after effects", category: "Technology" },
  { word: "premiere pro", category: "Technology" },
  { word: "final cut", category: "Technology" },
  { word: "davinci resolve", category: "Technology" },
  { word: "figma", category: "Technology" },
  { word: "sketch", category: "Technology" },
  { word: "adobe xd", category: "Technology" },
  { word: "invision", category: "Technology" },
  { word: "zeplin", category: "Technology" },
  { word: "slack", category: "Technology" },
  { word: "discord", category: "Technology" },
  { word: "teams", category: "Technology" },
  { word: "zoom", category: "Technology" },
  { word: "skype", category: "Technology" },
  { word: "whatsapp", category: "Technology" },
  { word: "telegram", category: "Technology" },
  { word: "signal", category: "Technology" },
  { word: "twitter", category: "Technology" },
  { word: "facebook", category: "Technology" },
  { word: "instagram", category: "Technology" },
  { word: "linkedin", category: "Technology" },
  { word: "youtube", category: "Technology" },
  { word: "tiktok", category: "Technology" },
  { word: "snapchat", category: "Technology" },
  { word: "pinterest", category: "Technology" },
  { word: "reddit", category: "Technology" },
  { word: "stackoverflow", category: "Technology" },
  { word: "wikipedia", category: "Technology" },
  { word: "google", category: "Technology" },
  { word: "bing", category: "Technology" },
  { word: "yahoo", category: "Technology" },
  { word: "duckduckgo", category: "Technology" },
  { word: "chrome", category: "Technology" },
  { word: "firefox", category: "Technology" },
  { word: "safari", category: "Technology" },
  { word: "edge", category: "Technology" },
  { word: "opera", category: "Technology" },

  // Science (100 words)
  { word: "oxygen", category: "Science" },
  { word: "hydrogen", category: "Science" },
  { word: "carbon", category: "Science" },
  { word: "nitrogen", category: "Science" },
  { word: "helium", category: "Science" },
  { word: "neon", category: "Science" },
  { word: "argon", category: "Science" },
  { word: "krypton", category: "Science" },
  { word: "xenon", category: "Science" },
  { word: "radon", category: "Science" },
  { word: "fluorine", category: "Science" },
  { word: "chlorine", category: "Science" },
  { word: "bromine", category: "Science" },
  { word: "iodine", category: "Science" },
  { word: "astatine", category: "Science" },
  { word: "lithium", category: "Science" },
  { word: "sodium", category: "Science" },
  { word: "potassium", category: "Science" },
  { word: "rubidium", category: "Science" },
  { word: "cesium", category: "Science" },
  { word: "francium", category: "Science" },
  { word: "beryllium", category: "Science" },
  { word: "magnesium", category: "Science" },
  { word: "calcium", category: "Science" },
  { word: "strontium", category: "Science" },
  { word: "barium", category: "Science" },
  { word: "radium", category: "Science" },
  { word: "aluminum", category: "Science" },
  { word: "silicon", category: "Science" },
  { word: "phosphorus", category: "Science" },
  { word: "sulfur", category: "Science" },
  { word: "iron", category: "Science" },
  { word: "copper", category: "Science" },
  { word: "zinc", category: "Science" },
  { word: "silver", category: "Science" },
  { word: "gold", category: "Science" },
  { word: "mercury", category: "Science" },
  { word: "lead", category: "Science" },
  { word: "uranium", category: "Science" },
  { word: "plutonium", category: "Science" },
  { word: "molecule", category: "Science" },
  { word: "atom", category: "Science" },
  { word: "electron", category: "Science" },
  { word: "proton", category: "Science" },
  { word: "neutron", category: "Science" },
  { word: "nucleus", category: "Science" },
  { word: "isotope", category: "Science" },
  { word: "radioactive", category: "Science" },
  { word: "photon", category: "Science" },
  { word: "quantum", category: "Science" },
  { word: "gravity", category: "Science" },
  { word: "magnetism", category: "Science" },
  { word: "electricity", category: "Science" },
  { word: "energy", category: "Science" },
  { word: "force", category: "Science" },
  { word: "momentum", category: "Science" },
  { word: "acceleration", category: "Science" },
  { word: "velocity", category: "Science" },
  { word: "frequency", category: "Science" },
  { word: "wavelength", category: "Science" },
  { word: "amplitude", category: "Science" },
  { word: "refraction", category: "Science" },
  { word: "reflection", category: "Science" },
  { word: "diffraction", category: "Science" },
  { word: "interference", category: "Science" },
  { word: "polarization", category: "Science" },
  { word: "spectrum", category: "Science" },
  { word: "laser", category: "Science" },
  { word: "fiber optic", category: "Science" },
  { word: "semiconductor", category: "Science" },
  { word: "transistor", category: "Science" },
  { word: "diode", category: "Science" },
  { word: "capacitor", category: "Science" },
  { word: "resistor", category: "Science" },
  { word: "inductor", category: "Science" },
  { word: "circuit", category: "Science" },
  { word: "voltage", category: "Science" },
  { word: "current", category: "Science" },
  { word: "resistance", category: "Science" },
  { word: "conductance", category: "Science" },
  { word: "magnetic field", category: "Science" },
  { word: "electric field", category: "Science" },
  { word: "electromagnetic", category: "Science" },
  { word: "thermodynamics", category: "Science" },
  { word: "entropy", category: "Science" },
  { word: "enthalpy", category: "Science" },
  { word: "catalyst", category: "Science" },
  { word: "enzyme", category: "Science" },
  { word: "protein", category: "Science" },
  { word: "amino acid", category: "Science" },
  { word: "dna", category: "Science" },
  { word: "rna", category: "Science" },
  { word: "chromosome", category: "Science" },
  { word: "gene", category: "Science" },
  { word: "mutation", category: "Science" },
  { word: "evolution", category: "Science" },
  { word: "natural selection", category: "Science" },
  { word: "adaptation", category: "Science" },
  { word: "species", category: "Science" },
  { word: "ecosystem", category: "Science" },
  { word: "biodiversity", category: "Science" },
  { word: "photosynthesis", category: "Science" },
  { word: "respiration", category: "Science" },
  { word: "mitosis", category: "Science" },
  { word: "meiosis", category: "Science" },

  // Music (100 words)
  { word: "guitar", category: "Music" },
  { word: "piano", category: "Music" },
  { word: "violin", category: "Music" },
  { word: "cello", category: "Music" },
  { word: "viola", category: "Music" },
  { word: "bass", category: "Music" },
  { word: "drums", category: "Music" },
  { word: "trumpet", category: "Music" },
  { word: "trombone", category: "Music" },
  { word: "saxophone", category: "Music" },
  { word: "clarinet", category: "Music" },
  { word: "flute", category: "Music" },
  { word: "oboe", category: "Music" },
  { word: "bassoon", category: "Music" },
  { word: "french horn", category: "Music" },
  { word: "tuba", category: "Music" },
  { word: "piccolo", category: "Music" },
  { word: "recorder", category: "Music" },
  { word: "harmonica", category: "Music" },
  { word: "accordion", category: "Music" },
  { word: "banjo", category: "Music" },
  { word: "mandolin", category: "Music" },
  { word: "ukulele", category: "Music" },
  { word: "harp", category: "Music" },
  { word: "organ", category: "Music" },
  { word: "keyboard", category: "Music" },
  { word: "synthesizer", category: "Music" },
  { word: "xylophone", category: "Music" },
  { word: "marimba", category: "Music" },
  { word: "vibraphone", category: "Music" },
  { word: "timpani", category: "Music" },
  { word: "cymbals", category: "Music" },
  { word: "triangle", category: "Music" },
  { word: "tambourine", category: "Music" },
  { word: "castanets", category: "Music" },
  { word: "maracas", category: "Music" },
  { word: "bongos", category: "Music" },
  { word: "congas", category: "Music" },
  { word: "djembe", category: "Music" },
  { word: "tabla", category: "Music" },
  { word: "sitar", category: "Music" },
  { word: "didgeridoo", category: "Music" },
  { word: "bagpipes", category: "Music" },
  { word: "ocarina", category: "Music" },
  { word: "kazoo", category: "Music" },
  { word: "melody", category: "Music" },
  { word: "harmony", category: "Music" },
  { word: "rhythm", category: "Music" },
  { word: "tempo", category: "Music" },
  { word: "beat", category: "Music" },
  { word: "measure", category: "Music" },
  { word: "chord", category: "Music" },
  { word: "scale", category: "Music" },
  { word: "key", category: "Music" },
  { word: "note", category: "Music" },
  { word: "sharp", category: "Music" },
  { word: "flat", category: "Music" },
  { word: "natural", category: "Music" },
  { word: "major", category: "Music" },
  { word: "minor", category: "Music" },
  { word: "octave", category: "Music" },
  { word: "interval", category: "Music" },
  { word: "unison", category: "Music" },
  { word: "dissonance", category: "Music" },
  { word: "consonance", category: "Music" },
  { word: "cadence", category: "Music" },
  { word: "modulation", category: "Music" },
  { word: "transposition", category: "Music" },
  { word: "improvisation", category: "Music" },
  { word: "composition", category: "Music" },
  { word: "arrangement", category: "Music" },
  { word: "orchestration", category: "Music" },
  { word: "conductor", category: "Music" },
  { word: "orchestra", category: "Music" },
  { word: "symphony", category: "Music" },
  { word: "concerto", category: "Music" },
  { word: "sonata", category: "Music" },
  { word: "fugue", category: "Music" },
  { word: "canon", category: "Music" },
  { word: "prelude", category: "Music" },
  { word: "etude", category: "Music" },
  { word: "nocturne", category: "Music" },
  { word: "waltz", category: "Music" },
  { word: "tango", category: "Music" },
  { word: "blues", category: "Music" },
  { word: "jazz", category: "Music" },
  { word: "rock", category: "Music" },
  { word: "pop", category: "Music" },
  { word: "classical", category: "Music" },
  { word: "baroque", category: "Music" },
  { word: "romantic", category: "Music" },
  { word: "modern", category: "Music" },
  { word: "contemporary", category: "Music" },
  { word: "folk", category: "Music" },
  { word: "country", category: "Music" },
  { word: "reggae", category: "Music" },
  { word: "hip hop", category: "Music" },
  { word: "rap", category: "Music" },
  { word: "electronic", category: "Music" },
  { word: "ambient", category: "Music" },
  { word: "techno", category: "Music" },
  { word: "house", category: "Music" },
  { word: "dubstep", category: "Music" },
  { word: "trance", category: "Music" },

  // Space (100 words)
  { word: "mars", category: "Space" },
  { word: "venus", category: "Space" },
  { word: "mercury", category: "Space" },
  { word: "earth", category: "Space" },
  { word: "jupiter", category: "Space" },
  { word: "saturn", category: "Space" },
  { word: "uranus", category: "Space" },
  { word: "neptune", category: "Space" },
  { word: "pluto", category: "Space" },
  { word: "sun", category: "Space" },
  { word: "moon", category: "Space" },
  { word: "asteroid", category: "Space" },
  { word: "comet", category: "Space" },
  { word: "meteor", category: "Space" },
  { word: "meteorite", category: "Space" },
  { word: "nebula", category: "Space" },
  { word: "galaxy", category: "Space" },
  { word: "milky way", category: "Space" },
  { word: "andromeda", category: "Space" },
  { word: "black hole", category: "Space" },
  { word: "white dwarf", category: "Space" },
  { word: "red giant", category: "Space" },
  { word: "supernova", category: "Space" },
  { word: "pulsar", category: "Space" },
  { word: "quasar", category: "Space" },
  { word: "neutron star", category: "Space" },
  { word: "binary star", category: "Space" },
  { word: "constellation", category: "Space" },
  { word: "orion", category: "Space" },
  { word: "big dipper", category: "Space" },
  { word: "cassiopeia", category: "Space" },
  { word: "polaris", category: "Space" },
  { word: "sirius", category: "Space" },
  { word: "betelgeuse", category: "Space" },
  { word: "rigel", category: "Space" },
  { word: "vega", category: "Space" },
  { word: "altair", category: "Space" },
  { word: "proxima centauri", category: "Space" },
  { word: "alpha centauri", category: "Space" },
  { word: "solar system", category: "Space" },
  { word: "orbit", category: "Space" },
  { word: "rotation", category: "Space" },
  { word: "revolution", category: "Space" },
  { word: "eclipse", category: "Space" },
  { word: "lunar eclipse", category: "Space" },
  { word: "solar eclipse", category: "Space" },
  { word: "crater", category: "Space" },
  { word: "maria", category: "Space" },
  { word: "apollo", category: "Space" },
  { word: "nasa", category: "Space" },
  { word: "esa", category: "Space" },
  { word: "spacex", category: "Space" },
  { word: "rocket", category: "Space" },
  { word: "shuttle", category: "Space" },
  { word: "capsule", category: "Space" },
  { word: "satellite", category: "Space" },
  { word: "space station", category: "Space" },
  { word: "iss", category: "Space" },
  { word: "mir", category: "Space" },
  { word: "hubble", category: "Space" },
  { word: "telescope", category: "Space" },
  { word: "spacewalk", category: "Space" },
  { word: "astronaut", category: "Space" },
  { word: "cosmonaut", category: "Space" },
  { word: "zero gravity", category: "Space" },
  { word: "weightlessness", category: "Space" },
  { word: "launch pad", category: "Space" },
  { word: "mission control", category: "Space" },
  { word: "countdown", category: "Space" },
  { word: "liftoff", category: "Space" },
  { word: "reentry", category: "Space" },
  { word: "heat shield", category: "Space" },
  { word: "parachute", category: "Space" },
  { word: "splashdown", category: "Space" },
  { word: "landing", category: "Space" },
  { word: "rover", category: "Space" },
  { word: "curiosity", category: "Space" },
  { word: "perseverance", category: "Space" },
  { word: "opportunity", category: "Space" },
  { word: "spirit", category: "Space" },
  { word: "voyager", category: "Space" },
  { word: "pioneer", category: "Space" },
  { word: "cassini", category: "Space" },
  { word: "galileo", category: "Space" },
  { word: "juno", category: "Space" },
  { word: "new horizons", category: "Space" },
  { word: "kepler", category: "Space" },
  { word: "spitzer", category: "Space" },
  { word: "chandra", category: "Space" },
  { word: "james webb", category: "Space" },
  { word: "exoplanet", category: "Space" },
  { word: "habitable zone", category: "Space" },
  { word: "goldilocks zone", category: "Space" },
  { word: "kepler 452b", category: "Space" },
  { word: "trappist-1", category: "Space" },
  { word: "light year", category: "Space" },
  { word: "parsec", category: "Space" },
  { word: "astronomical unit", category: "Space" },
  { word: "cosmic radiation", category: "Space" },
  { word: "solar wind", category: "Space" },
  { word: "magnetosphere", category: "Space" },
  { word: "atmosphere", category: "Space" },
  { word: "ionosphere", category: "Space" },
  { word: "thermosphere", category: "Space" },
  { word: "stratosphere", category: "Space" },
  { word: "troposphere", category: "Space" },
  { word: "ozone layer", category: "Space" },
  { word: "aurora", category: "Space" },
  { word: "northern lights", category: "Space" },
  { word: "southern lights", category: "Space" },
  { word: "solar flare", category: "Space" },
  { word: "coronal mass ejection", category: "Space" },
  { word: "sunspot", category: "Space" },
  { word: "solar cycle", category: "Space" },
  { word: "dark matter", category: "Space" },
  { word: "dark energy", category: "Space" },
  { word: "cosmic microwave background", category: "Space" },
  { word: "big bang", category: "Space" },
  { word: "redshift", category: "Space" },
  { word: "doppler effect", category: "Space" },
  { word: "expansion", category: "Space" },
  { word: "universe", category: "Space" },
  { word: "multiverse", category: "Space" },
  { word: "space time", category: "Space" },
  { word: "relativity", category: "Space" },
  { word: "wormhole", category: "Space" },
  { word: "event horizon", category: "Space" },

  // Sports (100 words)
  { word: "football", category: "Sports" },
  { word: "basketball", category: "Sports" },
  { word: "baseball", category: "Sports" },
  { word: "soccer", category: "Sports" },
  { word: "tennis", category: "Sports" },
  { word: "golf", category: "Sports" },
  { word: "hockey", category: "Sports" },
  { word: "volleyball", category: "Sports" },
  { word: "swimming", category: "Sports" },
  { word: "running", category: "Sports" },
  { word: "cycling", category: "Sports" },
  { word: "boxing", category: "Sports" },
  { word: "wrestling", category: "Sports" },
  { word: "martial arts", category: "Sports" },
  { word: "karate", category: "Sports" },
  { word: "judo", category: "Sports" },
  { word: "taekwondo", category: "Sports" },
  { word: "fencing", category: "Sports" },
  { word: "archery", category: "Sports" },
  { word: "gymnastics", category: "Sports" },
  { word: "diving", category: "Sports" },
  { word: "surfing", category: "Sports" },
  { word: "skiing", category: "Sports" },
  { word: "snowboarding", category: "Sports" },
  { word: "skating", category: "Sports" },
  { word: "figure skating", category: "Sports" },
  { word: "speed skating", category: "Sports" },
  { word: "roller skating", category: "Sports" },
  { word: "skateboarding", category: "Sports" },
  { word: "track and field", category: "Sports" },
  { word: "marathon", category: "Sports" },
  { word: "triathlon", category: "Sports" },
  { word: "decathlon", category: "Sports" },
  { word: "pentathlon", category: "Sports" },
  { word: "javelin", category: "Sports" },
  { word: "shot put", category: "Sports" },
  { word: "discus", category: "Sports" },
  { word: "hammer throw", category: "Sports" },
  { word: "pole vault", category: "Sports" },
  { word: "high jump", category: "Sports" },
  { word: "long jump", category: "Sports" },
  { word: "triple jump", category: "Sports" },
  { word: "hurdles", category: "Sports" },
  { word: "steeplechase", category: "Sports" },
  { word: "relay", category: "Sports" },
  { word: "sprint", category: "Sports" },
  { word: "distance", category: "Sports" },
  { word: "cross country", category: "Sports" },
  { word: "weightlifting", category: "Sports" },
  { word: "powerlifting", category: "Sports" },
  { word: "bodybuilding", category: "Sports" },
  { word: "crossfit", category: "Sports" },
  { word: "rock climbing", category: "Sports" },
  { word: "mountaineering", category: "Sports" },
  { word: "hiking", category: "Sports" },
  { word: "kayaking", category: "Sports" },
  { word: "canoeing", category: "Sports" },
  { word: "rowing", category: "Sports" },
  { word: "sailing", category: "Sports" },
  { word: "windsurfing", category: "Sports" },
  { word: "kitesurfing", category: "Sports" },
  { word: "water skiing", category: "Sports" },
  { word: "wakeboarding", category: "Sports" },
  { word: "scuba diving", category: "Sports" },
  { word: "snorkeling", category: "Sports" },
  { word: "fishing", category: "Sports" },
  { word: "hunting", category: "Sports" },
  { word: "equestrian", category: "Sports" },
  { word: "dressage", category: "Sports" },
  { word: "show jumping", category: "Sports" },
  { word: "polo", category: "Sports" },
  { word: "rodeo", category: "Sports" },
  { word: "racing", category: "Sports" },
  { word: "formula one", category: "Sports" },
  { word: "nascar", category: "Sports" },
  { word: "motocross", category: "Sports" },
  { word: "bmx", category: "Sports" },
  { word: "mountain biking", category: "Sports" },
  { word: "badminton", category: "Sports" },
  { word: "table tennis", category: "Sports" },
  { word: "squash", category: "Sports" },
  { word: "racquetball", category: "Sports" },
  { word: "handball", category: "Sports" },
  { word: "water polo", category: "Sports" },
  { word: "lacrosse", category: "Sports" },
  { word: "field hockey", category: "Sports" },
  { word: "rugby", category: "Sports" },
  { word: "cricket", category: "Sports" },
  { word: "bowling", category: "Sports" },
  { word: "billiards", category: "Sports" },
  { word: "pool", category: "Sports" },
  { word: "snooker", category: "Sports" },
  { word: "darts", category: "Sports" },
  { word: "chess", category: "Sports" },
  { word: "checkers", category: "Sports" },
  { word: "backgammon", category: "Sports" },
  { word: "poker", category: "Sports" },
  { word: "bridge", category: "Sports" },
  { word: "esports", category: "Sports" },
  { word: "gaming", category: "Sports" },
  { word: "cheerleading", category: "Sports" },
  { word: "dance", category: "Sports" },
  { word: "ballroom dancing", category: "Sports" },
  { word: "breakdancing", category: "Sports" },

  // Food (100 words)
  { word: "pizza", category: "Food" },
  { word: "burger", category: "Food" },
  { word: "pasta", category: "Food" },
  { word: "sushi", category: "Food" },
  { word: "sandwich", category: "Food" },
  { word: "salad", category: "Food" },
  { word: "soup", category: "Food" },
  { word: "steak", category: "Food" },
  { word: "chicken", category: "Food" },
  { word: "fish", category: "Food" },
  { word: "shrimp", category: "Food" },
  { word: "lobster", category: "Food" },
  { word: "crab", category: "Food" },
  { word: "salmon", category: "Food" },
  { word: "tuna", category: "Food" },
  { word: "beef", category: "Food" },
  { word: "pork", category: "Food" },
  { word: "lamb", category: "Food" },
  { word: "turkey", category: "Food" },
  { word: "duck", category: "Food" },
  { word: "bacon", category: "Food" },
  { word: "sausage", category: "Food" },
  { word: "hot dog", category: "Food" },
  { word: "ham", category: "Food" },
  { word: "cheese", category: "Food" },
  { word: "butter", category: "Food" },
  { word: "milk", category: "Food" },
  { word: "yogurt", category: "Food" },
  { word: "ice cream", category: "Food" },
  { word: "chocolate", category: "Food" },
  { word: "cake", category: "Food" },
  { word: "cookie", category: "Food" },
  { word: "pie", category: "Food" },
  { word: "donut", category: "Food" },
  { word: "muffin", category: "Food" },
  { word: "bagel", category: "Food" },
  { word: "croissant", category: "Food" },
  { word: "bread", category: "Food" },
  { word: "toast", category: "Food" },
  { word: "pancake", category: "Food" },
  { word: "waffle", category: "Food" },
  { word: "cereal", category: "Food" },
  { word: "oatmeal", category: "Food" },
  { word: "egg", category: "Food" },
  { word: "omelet", category: "Food" },
  { word: "scrambled eggs", category: "Food" },
  { word: "fried egg", category: "Food" },
  { word: "boiled egg", category: "Food" },
  { word: "poached egg", category: "Food" },
  { word: "rice", category: "Food" },
  { word: "noodles", category: "Food" },
  { word: "ramen", category: "Food" },
  { word: "spaghetti", category: "Food" },
  { word: "lasagna", category: "Food" },
  { word: "macaroni", category: "Food" },
  { word: "tacos", category: "Food" },
  { word: "burrito", category: "Food" },
  { word: "quesadilla", category: "Food" },
  { word: "nachos", category: "Food" },
  { word: "guacamole", category: "Food" },
  { word: "salsa", category: "Food" },
  { word: "curry", category: "Food" },
  { word: "pad thai", category: "Food" },
  { word: "stir fry", category: "Food" },
  { word: "fried rice", category: "Food" },
  { word: "dim sum", category: "Food" },
  { word: "spring roll", category: "Food" },
  { word: "tempura", category: "Food" },
  { word: "sashimi", category: "Food" },
  { word: "maki", category: "Food" },
  { word: "nigiri", category: "Food" },
  { word: "wasabi", category: "Food" },
  { word: "ginger", category: "Food" },
  { word: "soy sauce", category: "Food" },
  { word: "teriyaki", category: "Food" },
  { word: "barbecue", category: "Food" },
  { word: "grill", category: "Food" },
  { word: "roast", category: "Food" },
  { word: "bake", category: "Food" },
  { word: "fry", category: "Food" },
  { word: "boil", category: "Food" },
  { word: "steam", category: "Food" },
  { word: "saute", category: "Food" },
  { word: "braised", category: "Food" },
  { word: "marinated", category: "Food" },
  { word: "seasoned", category: "Food" },
  { word: "spicy", category: "Food" },
  { word: "mild", category: "Food" },
  { word: "sweet", category: "Food" },
  { word: "sour", category: "Food" },
  { word: "bitter", category: "Food" },
  { word: "salty", category: "Food" },
  { word: "umami", category: "Food" },
  { word: "appetizer", category: "Food" },
  { word: "entree", category: "Food" },
  { word: "main course", category: "Food" },
  { word: "side dish", category: "Food" },
  { word: "dessert", category: "Food" },
  { word: "beverage", category: "Food" },
  { word: "coffee", category: "Food" },
  { word: "tea", category: "Food" },
  { word: "juice", category: "Food" },
  { word: "soda", category: "Food" },
  { word: "water", category: "Food" },
  { word: "wine", category: "Food" },
  { word: "beer", category: "Food" },
  { word: "cocktail", category: "Food" },

  // Colors (100 words)
  { word: "red", category: "Color" },
  { word: "blue", category: "Color" },
  { word: "green", category: "Color" },
  { word: "yellow", category: "Color" },
  { word: "orange", category: "Color" },
  { word: "purple", category: "Color" },
  { word: "pink", category: "Color" },
  { word: "brown", category: "Color" },
  { word: "black", category: "Color" },
  { word: "white", category: "Color" },
  { word: "gray", category: "Color" },
  { word: "grey", category: "Color" },
  { word: "silver", category: "Color" },
  { word: "gold", category: "Color" },
  { word: "bronze", category: "Color" },
  { word: "copper", category: "Color" },
  { word: "maroon", category: "Color" },
  { word: "burgundy", category: "Color" },
  { word: "crimson", category: "Color" },
  { word: "scarlet", category: "Color" },
  { word: "ruby", category: "Color" },
  { word: "cherry", category: "Color" },
  { word: "rose", category: "Color" },
  { word: "coral", category: "Color" },
  { word: "salmon", category: "Color" },
  { word: "peach", category: "Color" },
  { word: "apricot", category: "Color" },
  { word: "tangerine", category: "Color" },
  { word: "amber", category: "Color" },
  { word: "honey", category: "Color" },
  { word: "mustard", category: "Color" },
  { word: "lemon", category: "Color" },
  { word: "lime", category: "Color" },
  { word: "chartreuse", category: "Color" },
  { word: "olive", category: "Color" },
  { word: "forest", category: "Color" },
  { word: "emerald", category: "Color" },
  { word: "jade", category: "Color" },
  { word: "mint", category: "Color" },
  { word: "seafoam", category: "Color" },
  { word: "teal", category: "Color" },
  { word: "turquoise", category: "Color" },
  { word: "aqua", category: "Color" },
  { word: "cyan", category: "Color" },
  { word: "sky blue", category: "Color" },
  { word: "powder blue", category: "Color" },
  { word: "baby blue", category: "Color" },
  { word: "royal blue", category: "Color" },
  { word: "navy", category: "Color" },
  { word: "midnight", category: "Color" },
  { word: "cobalt", category: "Color" },
  { word: "sapphire", category: "Color" },
  { word: "indigo", category: "Color" },
  { word: "violet", category: "Color" },
  { word: "lavender", category: "Color" },
  { word: "lilac", category: "Color" },
  { word: "plum", category: "Color" },
  { word: "magenta", category: "Color" },
  { word: "fuchsia", category: "Color" },
  { word: "hot pink", category: "Color" },
  { word: "blush", category: "Color" },
  { word: "dusty rose", category: "Color" },
  { word: "mauve", category: "Color" },
  { word: "taupe", category: "Color" },
  { word: "beige", category: "Color" },
  { word: "tan", category: "Color" },
  { word: "khaki", category: "Color" },
  { word: "sand", category: "Color" },
  { word: "wheat", category: "Color" },
  { word: "cream", category: "Color" },
  { word: "ivory", category: "Color" },
  { word: "pearl", category: "Color" },
  { word: "off white", category: "Color" },
  { word: "eggshell", category: "Color" },
  { word: "vanilla", category: "Color" },
  { word: "champagne", category: "Color" },
  { word: "sepia", category: "Color" },
  { word: "mocha", category: "Color" },
  { word: "coffee", category: "Color" },
  { word: "chocolate", category: "Color" },
  { word: "espresso", category: "Color" },
  { word: "mahogany", category: "Color" },
  { word: "chestnut", category: "Color" },
  { word: "russet", category: "Color" },
  { word: "burnt orange", category: "Color" },
  { word: "rust", category: "Color" },
  { word: "brick", category: "Color" },
  { word: "terra cotta", category: "Color" },
  { word: "sienna", category: "Color" },
  { word: "umber", category: "Color" },
  { word: "charcoal", category: "Color" },
  { word: "slate", category: "Color" },
  { word: "steel", category: "Color" },
  { word: "gunmetal", category: "Color" },
  { word: "pewter", category: "Color" },
  { word: "platinum", category: "Color" },
  { word: "neon", category: "Color" },
  { word: "electric", category: "Color" },
  { word: "fluorescent", category: "Color" },
  { word: "pastel", category: "Color" },
  { word: "muted", category: "Color" },
  { word: "vibrant", category: "Color" },
  { word: "bold", category: "Color" },
  { word: "subtle", category: "Color" },
  { word: "neutral", category: "Color" },

  // Professions (100 words)
  { word: "doctor", category: "Profession" },
  { word: "nurse", category: "Profession" },
  { word: "teacher", category: "Profession" },
  { word: "engineer", category: "Profession" },
  { word: "lawyer", category: "Profession" },
  { word: "police officer", category: "Profession" },
  { word: "firefighter", category: "Profession" },
  { word: "paramedic", category: "Profession" },
  { word: "pilot", category: "Profession" },
  { word: "chef", category: "Profession" },
  { word: "artist", category: "Profession" },
  { word: "writer", category: "Profession" },
  { word: "journalist", category: "Profession" },
  { word: "photographer", category: "Profession" },
  { word: "musician", category: "Profession" },
  { word: "actor", category: "Profession" },
  { word: "director", category: "Profession" },
  { word: "producer", category: "Profession" },
  { word: "architect", category: "Profession" },
  { word: "carpenter", category: "Profession" },
  { word: "plumber", category: "Profession" },
  { word: "electrician", category: "Profession" },
  { word: "mechanic", category: "Profession" },
  { word: "farmer", category: "Profession" },
  { word: "veterinarian", category: "Profession" },
  { word: "dentist", category: "Profession" },
  { word: "pharmacist", category: "Profession" },
  { word: "therapist", category: "Profession" },
  { word: "psychologist", category: "Profession" },
  { word: "counselor", category: "Profession" },
  { word: "social worker", category: "Profession" },
  { word: "accountant", category: "Profession" },
  { word: "banker", category: "Profession" },
  { word: "real estate agent", category: "Profession" },
  { word: "sales representative", category: "Profession" },
  { word: "manager", category: "Profession" },
  { word: "executive", category: "Profession" },
  { word: "consultant", category: "Profession" },
  { word: "analyst", category: "Profession" },
  { word: "programmer", category: "Profession" },
  { word: "software developer", category: "Profession" },
  { word: "web designer", category: "Profession" },
  { word: "graphic designer", category: "Profession" },
  { word: "data scientist", category: "Profession" },
  { word: "research scientist", category: "Profession" },
  { word: "librarian", category: "Profession" },
  { word: "secretary", category: "Profession" },
  { word: "receptionist", category: "Profession" },
  { word: "clerk", category: "Profession" },
  { word: "cashier", category: "Profession" },
  { word: "waiter", category: "Profession" },
  { word: "bartender", category: "Profession" },
  { word: "barista", category: "Profession" },
  { word: "delivery driver", category: "Profession" },
  { word: "taxi driver", category: "Profession" },
  { word: "bus driver", category: "Profession" },
  { word: "truck driver", category: "Profession" },
  { word: "construction worker", category: "Profession" },
  { word: "electrician", category: "Profession" },
  { word: "painter", category: "Profession" },
  { word: "roofer", category: "Profession" },
  { word: "landscaper", category: "Profession" },
  { word: "janitor", category: "Profession" },
  { word: "custodian", category: "Profession" },
  { word: "security guard", category: "Profession" },
  { word: "bouncer", category: "Profession" },
  { word: "detective", category: "Profession" },
  { word: "investigator", category: "Profession" },
  { word: "judge", category: "Profession" },
  { word: "attorney", category: "Profession" },
  { word: "paralegal", category: "Profession" },
  { word: "court reporter", category: "Profession" },
  { word: "bailiff", category: "Profession" },
  { word: "mayor", category: "Profession" },
  { word: "politician", category: "Profession" },
  { word: "diplomat", category: "Profession" },
  { word: "ambassador", category: "Profession" },
  { word: "military officer", category: "Profession" },
  { word: "soldier", category: "Profession" },
  { word: "sailor", category: "Profession" },
  { word: "marine", category: "Profession" },
  { word: "air force pilot", category: "Profession" },
  { word: "flight attendant", category: "Profession" },
  { word: "air traffic controller", category: "Profession" },
  { word: "travel agent", category: "Profession" },
  { word: "tour guide", category: "Profession" },
  { word: "hotel manager", category: "Profession" },
  { word: "concierge", category: "Profession" },
  { word: "event planner", category: "Profession" },
  { word: "wedding planner", category: "Profession" },
  { word: "florist", category: "Profession" },
  { word: "baker", category: "Profession" },
  { word: "butcher", category: "Profession" },
  { word: "fishmonger", category: "Profession" },
  { word: "grocer", category: "Profession" },
  { word: "shopkeeper", category: "Profession" },
  { word: "retail worker", category: "Profession" },
  { word: "fashion designer", category: "Profession" },
  { word: "tailor", category: "Profession" },
  { word: "seamstress", category: "Profession" },
  { word: "hairdresser", category: "Profession" },
  { word: "barber", category: "Profession" },
  { word: "beautician", category: "Profession" },
  { word: "massage therapist", category: "Profession" },
  { word: "personal trainer", category: "Profession" },
  { word: "coach", category: "Profession" },
  { word: "referee", category: "Profession" },
  { word: "umpire", category: "Profession" },
  ];

  res.status(200).json(wordPool);
}